services:
  api:
    container_name: api-docker
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${API_PORT}:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    container_name: prisma-postgres
    image: postgres:alpine
    restart: always
    env_file:
     - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    external: false