# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: jasper
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  db:
