# fly.toml app configuration file generated for phish-directory on 2025-02-02T18:01:53-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phish-directory'
primary_region = 'ewr'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
