openapi: "3.0.3"
info:
  title: "phish.directory"
  version: "0.0.1"
servers:
  - url: "https://api.phish.directory"
    description: "Production server"
  - url: "https://staging.phish.directory"
    description: "Staging server"
  - url: "http://localhost:3000"
    description: "Local development server"
paths:
