name: "Generate project activity report"
on:
  workflow_dispatch:
    inputs:
      since:
        description: "Since date (x months ago, yyyy-mm-dd)"
        type: string
        required: true
        default: "3 months ago"
      until:
        description: "Until date (now, x months ago, yyyy-mm-dd)"
        type: string
        required: true
        default: "now"
jobs:
  generate:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download external script
        run: |
          curl -o ./git-activity-report.sh https://raw.githubusercontent.com/phishdirectory/scripts/main/git-activity-report.sh
          chmod +x ./git-activity-report.sh
      - name: Generate report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          SINCE="${{ inputs.since }}" UNTIL="${{ inputs.until }}" bash ./git-activity-report.sh >> $GITHUB_STEP_SUMMARY
